name: Daily Pre‑Work Reminder

on:
  schedule:
    # Runs every day at 02:00 UTC → 18:00 PST
    - cron: '0 2 * * *'

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests icalendar python-dateutil

      - name: Run reminder script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          # Set this secret to 'true' if you only want tomorrow’s reminder
          ONLY_TOMORROW: ${{ secrets.ONLY_TOMORROW }}
        run: python bot.py
